name: Checking the input environment

on:
  workflow_dispatch:
    inputs:
      stages: 
        description: "Select Environment"
        required: true
        type: choice
        options:
          - dev
          - stage
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy the ENV
        run: echo "Deploy the Environment ${{ inputs.stages }}" 
          
        
