name: My First GitHub Actions Workflow

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la
      - name: List .github
        run: ls -al /home/runner/work/github_actions_lab/github_actions_lab/.github/workflows

      - name: Say Hello
        run: echo "Hello from GitHub Actions!"
