name: My First GitHub Actions Workflow
on:
  workflow_dispatch: 
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out
        run: actions/checkout@v4
      - name: Say Hello
        run: echo "Hello From GitHub Actions!"
      - name: Show current directory
        run: pwd
      - name: List The Files\
        run: ls -al
        
