name: test PR's based workflow trigger

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Run Tests
        run: echo "Runing test for PR"
