name: Runner Exploration

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@v4

      - name: current directory
        run: pwd

      - name: WorkSpace Variable
        run: echo "$GITHUB_WORKSPACE"
