name: Status Functions

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Step 1
        run: echo "Step 1 passed"

      - name: Intentional failure
        run: exit 1

      - name: Failure handler
        if: failure()
        run: echo "Something failed"

      - name: Always run
        if: always()
        run: echo "Cleanup/reporting step"
